### PR TITLE
solve blackout per https://groups.google.com/d/msg/islandora/ztY0Iv5-0AU...

### PR DESCRIPTION
**Pull request by ruebot**
Prevent blackout pdfs per [this](https://groups.google.com/d/msg/islandora/ztY0Iv5-0AU/B3rkrBEl8K8J) message from Roger Hyam.

### CODE REVIEW

**Comment by jonathangreen** [comment]
Do you have an example of a PDF that shows this problem we could maybe check into the repository into a fixtures folder? We are trying to collect good test cases that exhibit weird behavior, so we can get some automated testing in place.

**Comment by jonathangreen** [comment]
Thanks Nick.

**Comment by nigelgbanks** [comment]
Pulled it down and tested it, definitely fixes the problem.

**Comment by nigelgbanks** [comment]
I was thinking of issuing a separate pull request with the example files, but I'm not sure if we're allowed to distribute them?

**Comment by nigelgbanks** [comment]
Added a pull request so we don't loose them, tests to come later.

https://github.com/Islandora/islandora_solution_pack_pdf/pull/43

**Comment by qadan** [comment]
I'm currently doing up the PDF binary tests; I'll add in a check to see if the PREVIEW datastream is completely black, and use a PDF that currently has this issue as the fixture.

**Pull request merged**
