### PR TITLE
ISLANDORA-1824

### PR DESCRIPTION
**Pull request by uconnjeustis**
**JIRA Ticket**: (link)
[https://jira.duraspace.org/projects/ISLANDORA/issues/ISLANDORA-1824](https://jira.duraspace.org/projects/ISLANDORA/issues/ISLANDORA-1824)

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)
[Islandora Metadata Interest Group Notes on adding dateIssued](https://github.com/islandora-interest-groups/Islandora-Metadata-Interest-Group/blob/master/Meetings/12_12_2016.md)

# What does this Pull Request do?
The islandora_pdf_form_mods.xml includes the dateIssued field. This form would replace the existing default MODS XML form that doesn't have a dateIssued.

A brief description of what the intended result of the PR will be and/or what problem it solves.
All other default MODS xml forms have a dateIssued with the exception of the PDF and large image solution packs. This change will make the PDF default MODS xml form more consistent with other forms. It will also allow for more options beyond just dateCreated for users.

# What's new?
The only change was the addition of dateIssued as a textfield in the default MODS xml form.

# How should this be tested?
This was tested locally in the XML form builder. The result from the preview was copied to Oxygen to ensure that the mods xml was valid.

A description of what steps someone could take to:
* Download this MODS xml form
* Import this form in their site and associate it to the Islandora PDF content model
* Ingest a PDF using this default form to see that the dateIssued appears

# Additional Notes:
This change doesn't require any change in documentation, any change to dependencies, modifications to other code.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DonRichards** [comment]
The description does not match the changes. This is a maintainer name change and a drupal version change in the islandora_pdf.info. Was there other files intended for this PR?

**Comment by bryjbrown** [comment]
@DonRichards Also this looks like its trying to merge into the 7.x-1.8 branch. I'm pretty sure once a release is cut, it stays static and only the 1.x branch gets updated after that. Might want to check in w/ @DiegoPino on this.

**Comment by DiegoPino** [comment]
@DonRichards @bryjbrown. This one got trapped between releases. Would be easier and safer to @uconnjeustis to close this one and open a new one (copy and pasta same pull request message) against current HEAD. What do you all think? @uconnjeustis you feel this could be something you could do soon to avoid this happening again? Thanks to all involved =)

**Comment by uconnjeustis** [comment]
Hi all,

I'm a little late to this discussion. Does this concern the change to the
default MODS xml form for the PDF content model?

Jennifer

**Pull request closed without merging**
