### PR TITLE
screenshot adds the display for the gs path.

### PR DESCRIPTION
**Pull request by DonRichards**
**JIRA Ticket**: N/A

# What does this Pull Request do?
Replaces screenshot. The new screenshots shows that the GS path is editable. 

# What's new?
Switches the "confirmed" status for GS to show that the GS path is editable. 

# How should this be tested?
Look at admin/islandora/solution_pack_config/pdf to verify 

# Additional Notes:
N/A

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Review by DiegoPino — APPROVED** [review]
Great! crisp screenshots

**Comment by DonRichards** [comment]
Thanks.

**Comment by rosiel** [comment]
ping @DiegoPino  - this and https://github.com/Islandora/islandora_solution_pack_pdf/pull/134 look ready.

**Comment by DiegoPino** [comment]
@rosiel thanks, i almost forget about this. @DonRichards++ 4 pulls in day =)

**Pull request merged**
